name: familytree
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'
#3.10.5 version


dependencies:
  # FLUTTER
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # API
  dio: ^5.0.2
  http: ^0.13.5

  # HELPER
  equatable: 2.0.5
  logger: ^1.2.2
  device_info_plus: ^8.1.0
  package_info_plus: ^3.0.3
  shared_preferences: ^2.0.18
  get_it: 7.2.0
  flutter_dotenv: 5.0.2
  url_launcher: ^6.1.10
  formz: ^0.5.0+1
  flutter_screenutil: ^5.7.0
  uuid: ^3.0.7
  google_fonts: ^4.0.3
  intl: ^0.17.0
  
  # WIDGET
  modal_bottom_sheet: ^3.0.0-pre
  bot_toast: 4.0.3
  shimmer: 2.0.0
  auto_size_text: 3.0.0
  flutter_spinkit: ^5.1.0
  
  # STATE MANAGEMENT
  flutter_bloc: ^8.1.2
  auto_route: ^5.0.2


  # OTHER
  change_app_package_name: 1.1.0

  permission_handler: ^11.0.0
  image_picker: ^1.0.2
  firebase_core: ^2.11.0
  cloud_firestore: ^4.6.0
  firebase_storage: ^11.1.2
  graphview: ^1.2.0
  file_picker: ^5.2.6
  responsive_framework: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
  auto_route_generator: 5.0.3
  build_runner: ^2.3.3


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.


  assets:
    # Add assets from the images directory to the application.
    - assets/
